# Generated by Django 3.1 on 2020-10-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('iddocumento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo', models.BinaryField()),
                ('estado', models.FloatField()),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesoejecutado',
            fields=[
                ('idprocesoejecutado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaejecucion', models.DateField(blank=True, null=True)),
                ('fechatermino', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procesoejecutado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsabletarea',
            fields=[
                ('idresponsabletareausuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asignador', models.BigIntegerField()),
            ],
            options={
                'db_table': 'responsabletarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareaejecutada',
            fields=[
                ('idtareaejecutada', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('avance', models.BigIntegerField(blank=True, null=True)),
                ('duracion_dias', models.BigIntegerField(blank=True, null=True)),
                ('orden_tarea', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareaejecutada',
                'managed': False,
            },
        ),
    ]
