# Generated by Django 3.1 on 2020-10-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0002_auto_20201011_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.unidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.comuna'),
        ),
        migrations.AlterField(
            model_name='procesotipo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.unidad'),
        ),
        migrations.AlterField(
            model_name='tareatipo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.cargo'),
        ),
        migrations.AlterField(
            model_name='tareatipo',
            name='procesotipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.procesotipo'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwork.empresa'),
        ),
    ]
