# Generated by Django 3.1 on 2020-10-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0003_auto_20201012_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareatipo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='tareatipo',
            name='procesotipo',
        ),
    ]
